image: archlinux/base

variables:
        DOCKER_DRIVER: overlay2

build-linux:
        image: registry.gitlab.com/tracurate/tracurate-build-images:linux
        stage: build
        artifacts:
                paths:
                        - TraCurate.zip
        script:
                - export GIT_CLONE_PATH=`pwd`
                - cd /build
                - pacman -S --noconfirm which zip
                - git clone $GIT_CLONE_PATH tracurate
                - cp -ar "$GIT_CLONE_PATH" tracurate
                - ln -s tracurate/aux/Makefile.linux Makefile
                - mkdir build
                - make
                - cp TraCurate.zip $GIT_CLONE_PATH

build-windows:
        image: registry.gitlab.com/tracurate/tracurate-build-images:windows
        stage: build
        artifacts:
                paths:
                        - TraCurate.exe
        script:
                - export GIT_CLONE_PATH=`pwd`
                - cd /build
                - cp -ar "$GIT_CLONE_PATH" tracurate
                - ln -s tracurate/aux/Makefile.windows Makefile
                - export PATH="$(realpath mxe)/usr/bin:$PATH"
                - ls -lah mxe/usr/bin
                - make
                - cp TraCurate.exe $GIT_CLONE_PATH
