image: archlinux/base

variables:
        DOCKER_DRIVER: overlay2

build-linux:
        image: registry.gitlab.com/tracurate/tracurate-build-images:linux
        stage: build
        artifacts:
                paths:
                        - /build/TraCurate.zip
        only:
                - linux-build
        script:
                - export GIT_CLONE_PATH=`pwd`
                - cd /build
                - pacman -S --noconfirm which git zip
                - ls $GIT_CLONE_PATH
                - echo $GIT_CLONE_PATH
                - git clone $GIT_CLONE_PATH tracurate
                - cp -ar "$GIT_CLONE_PATH" tracurate
                #- (cd $GIT_CLONE_PATH && git branch -l)
                #- (cd tracurate && git branch -l)
                #- (cd tracurate && git checkout linux-build)
                - ln -s tracurate/aux/Makefile.linux Makefile
                - mkdir build
                - make

