image: archlinux/base

variables:
        DOCKER_DRIVER: overlay2

build-linux:
        image: registry.gitlab.com/tracurate/tracurate-build-images:linux
        stage: build
        artifacts:
                paths:
                        - TraCurate.zip
        tags:
                - linux
        script:
                - export GIT_CLONE_PATH=`pwd`
                - cd /build
                - pacman -S --noconfirm which zip git
                - cp -ar "$GIT_CLONE_PATH" tracurate
                - ln -s tracurate/aux/Makefile.linux Makefile
                - mkdir build
                - make
                - cp TraCurate.zip $GIT_CLONE_PATH

build-windows:
        image: registry.gitlab.com/tracurate/tracurate-build-images:windows
        stage: build
        artifacts:
                paths:
                        - TraCurate.exe
        tags:
                - windows
        script:
                - export GIT_CLONE_PATH=`pwd`
                - cd /build
                - cp -ar "$GIT_CLONE_PATH" tracurate
                - ln -s tracurate/aux/Makefile.windows Makefile
                - export PATH="$(realpath mxe)/usr/bin:$PATH"
                - make
                - cp TraCurate.exe $GIT_CLONE_PATH

build-osx:
        stage: build
        artifacts:
                paths:
                        - TraCurate.dmg
        tags:
                - osx
        script:
                - export GIT_CLONE_PATH=`pwd`
                - export BUILD_DIR=`mktemp -d`
                - export CPATH=/Library/Developer/CommandLineTools/usr/include/c++/v1
                - echo "Using tempdir $BUILD_DIR"
                - cd $BUILD_DIR
                - cp -a "$GIT_CLONE_PATH" tracurate
                - ln -s $HOME/dev/Qt5.8.0 Qt5.8.0
                - ln -s tracurate/aux/Makefile.osx Makefile
                - mkdir build deploy package
                - make
                - cp TraCurate.dmg $GIT_CLONE_PATH
                - cd $GIT_CLONE_PATH
                - rm -rf $BUILD_DIR
