image: archlinux/base

variables:
        DOCKER_DRIVER: overlay2
        APT_CACHE_DIR: "$CI_PROJECT_DIR/.cache/apt"
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        CONDA_PKGS_DIRS: "$CI_PROJECT_DIR/.cache/conda"

before_script:
        #- apt-get -o dir::cache::archives="$APT_CACHE_DIR" update -qy
        #- apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y ffmpeg cmake
        #- apt-get update -qy
        #- apt-get install -y ffmpeg cmake
        #- conda env create -f environment.yml
        #- source activate cellshapy
        #- python setup.py develop

tests:
        stage: deploy
        only:
                - linux-build
        script:
                - ls

#cache:
#        key: ${CI_COMMIT_REF_SLUG}
#        paths:
#                - .cache/apt
#                - .cache/pip
#                - .cache/conda

