image: archlinux/base

variables:
        DOCKER_DRIVER: overlay2
        APT_CACHE_DIR: "$CI_PROJECT_DIR/.cache/apt"
        PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
        CONDA_PKGS_DIRS: "$CI_PROJECT_DIR/.cache/conda"

before_script:
        - echo "Foo?"
        #- apt-get -o dir::cache::archives="$APT_CACHE_DIR" update -qy
        #- apt-get -o dir::cache::archives="$APT_CACHE_DIR" install -y ffmpeg cmake
        #- apt-get update -qy
        #- apt-get install -y ffmpeg cmake
        #- conda env create -f environment.yml
        #- source activate cellshapy
        #- python setup.py develop

build-linux:
        image: archlinux/base
        stage: build
        only: build-using-ci
        script:
                - cd ..
                - mkdir build Qt5.8.0-static
                - ln -s . tracurate
                - ln -s aux/Makefile.linux Makefile
                - cd Qt5.8.0-static
                - mkdir install
                - wget https://download.qt.io/archive/qt/5.8/5.8.0/single/qt-everywhere-opensource-src-5.8.0.tar.xz
                - tar xvf qt-everywhere-opensource-src-5.8.0.tar.xz


#cache:
#        key: ${CI_COMMIT_REF_SLUG}
#        paths:
#                - .cache/apt
#                - .cache/pip
#                - .cache/conda

