#include <QDebug>

#include "project.h"
#include "io/importhdf5.h"
#include "io/exporthdf5.h"
#include "exceptions/ctdependencyexception.h"

#include "examples.h"

void exampleSaveAllCombinations() {
    using namespace CellTracker;

    ImportHDF5 ih;
    std::shared_ptr<Project> proj = ih.load(EXAMPLE_SMALL_HDF5);

    ExportHDF5 eh;

    const int argc = 7;
    bool args[argc];
    for (int i = 0; i < (1<<argc); i++) {
        for (int idx = 0; idx < argc; idx++) {
            args[idx] = (i>>idx) % 2;
            std::cout << "args[" << idx << "]=" << (args[idx]?"true ":"false") << " ";
        }
        std::cout << "generated by " << i << std::endl;
        std::string name(EXAMPLE_WRITE_DIR);
        name += "/out";
        name += std::to_string(i);
        name += ".h5";

        std::cout << "saving " << name << std::endl;
        try {
            eh.save(proj, QString(name.c_str()), args[0], args[1], args[2], args[3], args[4], args[5], args[6]);
        } catch (CTDependencyException &e) {
            std::cout << "threw exception" << std::endl;
        } catch (std::exception &e) {
            std::cout << "unhandled exception with parameters generated from" << i << std::endl
                      << "exception" << e.what() << std::endl;
        }
    }

    exit(0);
}
