#include <QDebug>
#include <QDir>

#include "project.h"
#include "io/importhdf5.h"
#include "io/exporthdf5.h"
#include "exceptions/ctdependencyexception.h"

#include "examples.h"

void exampleSaveAllCombinations() {
    using namespace CellTracker;

    QDir d(EXAMPLE_WRITE_DIR);
    for (QString entry : d.entryList())
        d.remove(entry);

    const int argc = 7;
    bool args[argc];
    const char *names[] = {
        "sAnnotations",
        "sAutoTracklets",
        "sEvents",
        "sImages",
        "sInfo",
        "sObjects",
        "sTracklets" };
    for (int i = 0; i < (1<<argc); i++) {
        for (int idx = 0; idx < argc; idx++) {
            args[idx] = (i>>idx) % 2;
            std::cerr << names[idx] << "=" << (args[idx]?"true ":"false") << " ";
        }
        std::cerr << "generated by " << i << std::endl;
        std::string name(EXAMPLE_WRITE_DIR);
        name += "/out";
        name += std::to_string(i);
        name += ".h5";

        ImportHDF5 ih;
        ExportHDF5 eh;

        std::shared_ptr<Project> proj = ih.load(EXAMPLE_SMALL_HDF5);

        std::cerr << "saving " << name << std::endl;
        try {
            Export::SaveOptions so{args[0], args[1], args[2], args[3], args[4], args[5], args[6]};
            eh.save(proj, QString(name.c_str()), so);
            std::cerr << "went well";
        } catch (CTDependencyException &e) {
            std::cerr << "threw exception " << e.what() << std::endl;
        } catch (std::exception &e) {
            std::cerr << "unhandled exception with parameters generated from " << i << ": " << e.what() << std::endl;
        }
    }

    exit(0);
}
